services:
  mri_backend:
    image: node:20.19.3-bullseye-slim
    container_name: mri_backend
    tty: true
    restart: unless-stopped
    ports:
      - 13700:4000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /src:/app
      - /dist_public:/app/public
    env_file:
      - .prod.env
    working_dir: /app
    command: /bin/bash -c "npm install && npm run build && npm run start"
    networks:
      production:
        ipv4_address: 172.40.1.10
      net-database:
        ipv4_address: 172.30.1.6
      prod-database:
        ipv4_address: 172.55.1.6

networks:
  production:
    external: true
  net-database:
    external: true
  prod-database:
    external: true