services:
  mri_backend:
    image: mri_backend:002
    container_name: mri_backend
    tty: true
    restart: unless-stopped
    ports:
      - 13700:4000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env.prod
    working_dir: /app
    networks:
      production:
        ipv4_address: 172.40.1.10
      net-database:
        ipv4_address: 172.30.1.6
      prod-database:
        ipv4_address: 172.55.1.6

networks:
  production:
    external: true
  net-database:
    external: true
  prod-database:
    external: true